relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
kramdown:
  input: GFM
  parse_block_html: true
markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks"]
